Repository GetStream/stream-video-android, pull requests merged in 2025-05, with the labels that each got.

#1409 Release notes rules
  .github/release.yaml
Labels: pr:ignore-for-release

#1404 [AND-449] Fix: call controls not working on incoming and outgoing screens
  stream-video-android-ui-compose/api/stream-video-android-ui-compose.api
  stream-video-android-ui-compose/src/main/kotlin/io/getstream/video/android/compose/ui/components/call/ringing/incomingcall/IncomingCallContent.kt
  stream-video-android-ui-compose/src/main/kotlin/io/getstream/video/android/compose/ui/components/call/ringing/incomingcall/IncomingCallControls.kt
  stream-video-android-ui-core/api/stream-video-android-ui-core.api
  stream-video-android-ui-core/src/main/kotlin/io/getstream/video/android/ui/common/StreamCallActivity.kt
Labels: pr:bug

#1414 [CI] Implement Layout E2E tests
  .github/workflows/e2e-test.yml
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/robots/UserRobot.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/robots/UserRobotCallAsserts.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/LayoutTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/ParticipantActionsTests.kt
Labels: pr:ci

#1420 [AND-549] Improve call rejection/decline/timeout flow by fixing coroutines scope usage
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
Labels: pr:bug

#1416 [AND-545] Re-order state update sequence to prevent ending up in the wrong state
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
  stream-video-android-ui-core/src/main/kotlin/io/getstream/video/android/ui/common/StreamCallActivity.kt
Labels: pr:bug

#1415 [AND-544] Improve AudioSwitch activation
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/audio/AudioHandler.kt
Labels: pr:bug

#1421 [AND-545] Return the original query calls response as part of the original
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/internal/InternalStreamVideoApi.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/model/QueriedCalls.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/utils/DomainUtils.kt
Labels: pr:improvement

#1401 Automatically update version name for the google play app.
  buildSrc/src/main/kotlin/io/getstream/video/android/Configuration.kt
Labels: pr:ignore-for-release

#1424 Always show FloatingParticipantVideo in calls
  stream-video-android-ui-compose/src/main/kotlin/io/getstream/video/android/compose/ui/components/call/renderer/FloatingParticipantVideo.kt
Labels: pr:bug

#1423 [AND-554] Keep the needed calls separately to preserve updates.
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoClient.kt
Labels: pr:improvement

#1428 Fix workflow to publish the Demo App to Google Play
  .github/workflows/artifact-upload.yaml
  .github/workflows/internal-app-distribute.yml
  demo-app/build.gradle.kts
  gradle/libs.versions.toml
Labels: pr:ci

#1431 [CI] Implement user actions related E2E tests
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/pages/CallPage.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/robots/UserRobot.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/robots/UserRobotCallAsserts.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/rules/RetryRule.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/CallLifecycleTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/LayoutTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/ParticipantActionsTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/ReconnectionTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/StreamTestCase.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/tests/UserActionsTests.kt
  demo-app/src/androidTestE2etestingDebug/kotlin/io/getstream/video/android/uiautomator/Actions.kt
  demo-app/src/main/kotlin/io/getstream/video/android/ui/call/CallScreen.kt
  demo-app/src/main/kotlin/io/getstream/video/android/ui/menu/VideoFiltersMenu.kt
  demo-app/src/main/kotlin/io/getstream/video/android/ui/menu/base/DynamicMenu.kt
Labels: pr:ci

#1435 [AND-579]: Integrate Microphone Toggle in Host Interface
  tutorials/tutorial-livestream/src/main/kotlin/io/getstream/video/android/tutorial/livestream/LiveHost.kt
Labels: pr:demo-app
