Repository GetStream/stream-video-android, pull requests merged in 2025-09, with the labels that each got.

#1503 Improve handling of quick disconnect/reconnect by debouncing participantState UI collection
  stream-video-android-ui-core/api/stream-video-android-ui-core.api
  stream-video-android-ui-core/src/main/kotlin/io/getstream/video/android/ui/common/StreamCallActivity.kt
Labels: pr:improvement

#1518 Enhance retry handling for failed call joins.
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/internal/service/CallService.kt
Labels: pr:improvement

#1523 Expose the participant source to the `ParticipantState`
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/ParticipantState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/RtcSession.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/sorting/DefaultSortOrder.kt
  stream-video-android-core/src/main/proto/video/sfu/event/events.pb.go
  stream-video-android-core/src/main/proto/video/sfu/event/events.proto
  stream-video-android-core/src/main/proto/video/sfu/event/events_vtproto.pb.go
  stream-video-android-core/src/main/proto/video/sfu/models/models.pb.go
  stream-video-android-core/src/main/proto/video/sfu/models/models.proto
  stream-video-android-core/src/main/proto/video/sfu/models/models_vtproto.pb.go
  stream-video-android-core/src/main/proto/video/sfu/signal_rpc/signal.pb.go
Labels: pr:new-feature

#1514 Replace `webp` with an `xml` resource
  stream-video-android-ui-core/src/main/res/drawable/stream_video_call_sample.webp
  stream-video-android-ui-core/src/main/res/drawable/stream_video_call_sample.xml
Labels: pr:improvement

#1522 Improve the network disconnect detection
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/internal/network/NetworkStateProvider.kt
Labels: pr:improvement

#1524 Fixed an issue where the `foreground` service may not be canceled
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/ClientState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/internal/service/CallService.kt
Labels: pr:improvement

#1525 Update permission of stale workflow
  .github/workflows/pr-clean-old-drafts.yaml
Labels: pr:ignore-for-release

#1526 Add `AGENTS.md` file to the video repo
  AGENTS.md
Labels: pr:internal

#1528 Update `ownCapabilities` for local user only
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
Labels: pr:bug

#1529 Upgrade to v1.0.4 noise cancellation which supports 16kb page size
  gradle/libs.versions.toml
Labels: pr:improvement

#1508 Enhance SDK stability and memory efficiency in large rooms
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallActions.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/ParticipantState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/RtcSession.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Publisher.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnection.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionFactory.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Subscriber.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/scope/ScopeProvider.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/scope/ScopeProviderImpl.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/sorting/SortedParticipantsState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/utils/SerialProcessor.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/CallStateTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionFactoryTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/scope/ScopeProviderTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/utils/SerialProcessorTest.kt
  stream-video-android-previewdata/src/main/kotlin/io/getstream/video/android/mock/StreamPreviewDataUtils.kt
Labels: pr:improvement
