Repository GetStream/stream-video-android, pull requests merged in 2025-06, with the labels that each got.

#1432 [AND-472] Improve call lifecycle handling after user has declined a call on poor network
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
  stream-video-android-ui-core/src/main/kotlin/io/getstream/video/android/ui/common/StreamCallActivity.kt
Labels: pr:improvement

#1442 [AND-597] StreamCallActivity is now compatible with hilt
  stream-video-android-ui-core/api/stream-video-android-ui-core.api
  stream-video-android-ui-core/src/main/kotlin/io/getstream/video/android/ui/common/StreamCallActivity.kt
Labels: pr:improvement

#1445 Allow for the SDK to collect RTC stats if configured
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoBuilder.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoClient.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/RtcSession.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Publisher.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnection.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionFactory.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Subscriber.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/stats/StatsTracer.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/stats/RtcMapper.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/internal/module/ConnectionModuleDeclaration.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/internal/module/CoordinatorConnectionModule.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/internal/module/SfuConnectionModule.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/DefaultNotificationHandler.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/trace/InterfaceTracer.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/trace/PeerConnectionTraceKey.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/trace/TraceRecord.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/trace/TracerManager.kt
  stream-video-android-core/src/main/proto/video/sfu/event/events.pb.go
  stream-video-android-core/src/main/proto/video/sfu/event/events.proto
  stream-video-android-core/src/main/proto/video/sfu/event/events_vtproto.pb.go
  stream-video-android-core/src/main/proto/video/sfu/models/models.pb.go
  stream-video-android-core/src/main/proto/video/sfu/models/models.proto
  stream-video-android-core/src/main/proto/video/sfu/models/models_vtproto.pb.go
  stream-video-android-core/src/main/proto/video/sfu/signal_rpc/signal.pb.go
  stream-video-android-core/src/main/proto/video/sfu/signal_rpc/signal.proto
  stream-video-android-core/src/main/proto/video/sfu/signal_rpc/signal.twirp.go
  stream-video-android-core/src/main/proto/video/sfu/signal_rpc/signal_vtproto.pb.go
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/PublisherTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionFactoryTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/SubscriberTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/call/connection/stats/StatsTracerTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/trace/InterfaceTracerKtTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/trace/PeerConnectionTraceKeyTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/trace/TraceRecordTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/trace/TracerManagerTest.kt
Labels: pr:new-feature

#1458 Allow for stereo to be enabled if offered in the remote SDP while also improving tracing on the `Subscriber` negotiation process
  gradle/libs.versions.toml
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoBuilder.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoClient.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/RtcSession.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Publisher.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnection.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/StreamPeerConnectionFactory.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Subscriber.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/utils/StereoUtils.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/utils/EnableStereoTest.kt
Labels: pr:improvement

#1460 Ability to further customise the media notifications and possibly add media actions
  stream-video-android-core/api/stream-video-android-core.api
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/Call.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/call/connection/Subscriber.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/handlers/CompatibilityStreamNotificationHandler.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/handlers/StreamDefaultNotificationHandler.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/handlers/StreamMediaSessionController.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/handlers/StreamNotificationHandler.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/internal/service/CallService.kt
  stream-video-android-core/src/main/res/drawable/stream_video_ic_live_notification.xml
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/notifications/handlers/StreamMediaSessionControllerIntegrationTest.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/notifications/handlers/StreamNotificationUpdateInterceptorsTest.kt
Labels: pr:improvement

#1467 Debounce participant updates as the number of participant increases
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/CallState.kt
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/utils/TaskSchedulerWithDebounce.kt
  stream-video-android-core/src/test/kotlin/io/getstream/video/android/core/utils/TaskSchedulerWithDebounceTest.kt
Labels: pr:improvement

#1465 Improve destroyed calls event processing
  stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/StreamVideoClient.kt
Labels: pr:improvement

#1469 Update floating window when there are no remote participants
  stream-video-android-ui-compose/src/main/kotlin/io/getstream/video/android/compose/ui/components/call/renderer/internal/PortraitVideoRenderer.kt
Labels: pr:bug
